---
- name : install tomcat on ubuntu
  become : yes
  hosts : ubuntu
  tasks:
    - name : install java
      ansible.builtin.apt :
        name : "{{ java_package }}"
        update_cache: yes
        state : present
    - name : add group
      ansible.builtin.group:
        name : "{{ group_name }}"
        state : present
    - name: Add tomcat user on ubuntu
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home : true
        home : "{{ home_directory }}"
        group : "{{ group_name }}"
        shell : "{{ default_shell }}"
        state : present
    - name : download tomcat
      ansible.builtin.get_url:
        url: https://www-eu.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz 
        dest: /tmp
      
      
